<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
   <div class="col-md-12">
      <h1>Cadastrar nova despesa</h1>
   </div>
   <hr/>
   <div class="col-md-12">
   <form>
      <div class="form-group">
        <label for="price">Valor Gasto</label>
        <input type="text" class="form-control" id="price" placeholder="Valor Gasto" name="price">
      </div>      
      <div class="form-group">
         <label for="description">Descrição</label>
         <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
      </div>   
      <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
    </form>
    </div>
    </div>
    <?php require VIEWS_PATH . 'includes/footer.phtml';?>