<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
   <!-- Main component for a primary marketing message or call to action -->
   <div class="jumbotron">
        <h1>Bem vindo ao Projeto 1</h1>
        <p>
          Projeto criado  no curso PHP Orientado a Objetos da Code Experts learning.
        </p>
          <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </p>
      </div>

      <div class="col-md-12">
          <?php foreach ($this->products as $product): ?>
            <div class="col-md-4">
                <img src="http://via.placeholder.com/350x150?text=<?=$product['name']; ?>" alt="" class="img-responsive">
                <h2><a href="<?=HOME;?>/product/<?=$product['id']; ?>"><?=$product['name']; ?></a></h2>
                <p><?=$product['description']; ?></p>
                <p><?=number_format($product['price'],2,',','.'); ?></p>
            </div>

          <?php endforeach; ?>
      </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>